# Generated by Django 4.1.4 on 2023-03-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=255)),
                ('channelId', models.CharField(max_length=255)),
                ('channelTitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
