# Generated by Django 4.1.4 on 2023-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
