# Generated by Django 4.1.4 on 2023-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePictureUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
