# Generated by Django 4.1.4 on 2023-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_user_profilepictureurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileUsername',
            field=models.CharField(default='testUsername', max_length=30),
            preserve_default=False,
        ),
    ]
